// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title MockVerifier
 * @notice Development-only verifier that always returns true
 * @dev Replace with the real Groth16Verifier generated by:
 *      snarkjs zkey export solidityverifier circuit_final.zkey Groth16Verifier.sol
 */
contract MockVerifier {
    function verifyProof(
        uint[2] calldata,
        uint[2][2] calldata,
        uint[2] calldata,
        uint[1] calldata
    ) external pure returns (bool) {
        return true;
    }
}
