export { default as AdminPage } from './pages/AdminPage';
export { default as DepartmentsPage } from './pages/DepartmentsPage';
export { default as StaffPage } from './pages/StaffPage';
export { default as DoctorsPage } from './pages/DoctorsPage';
export { default as AiModelsPage } from './pages/AiModelsPage';
export { default as DeletedRecordsPage } from './pages/DeletedRecordsPage';
export { default as AuditLogsPage } from './pages/AuditLogsPage';
export { departmentService } from './apis/departmentService';
export { auditService } from './apis/auditService';
export { staffService } from './apis/staffService';
export { doctorService } from './apis/doctorService';
